#!/bin/bash
rm -rf components
mkdir components
git clone git@github.com:alphagov/govuk-frontend.git
cd govuk-frontend
# TODO: config option for tracking specific version
git checkout tags/v2.5.0

cd src/components/

for D in *; do
  if [ -d "${D}" ]; then
    echo "${D}"   # your processing here
    mkdir ../../../components/$D/
    cp $D/template.test.js ../../../components/$D/template.test.js
    cp $D/template.test.js ../../../components/$D/$D.yaml
  fi
done

cd ../../..
rm -rf govuk-frontend
sed -i '' 's/\.\.\/\.\.\/\.\.\/lib\/jest-helpers/\.\.\/\.\.\/lib\/jest-helpers/g' components/**/*.js
sed -i '' 's/\.\.\/\.\.\/\.\.\/lib\/axe-helper/\.\.\/\.\.\/lib\/axe-helper/g' components/**/*.js
